name: Deploy to AWS EC2
on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Deploy Application to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          set -e
          
          # Ensure app directory exists
          mkdir -p ~/app
          cd ~/app
          
          # Clone using SSH if repo does not exist
          if [ ! -d "app" ]; then
            git clone git@github.com:your-username/your-repo.git app
          fi
          cd app
          
          # Ensure GitHub host key is trusted
          ssh-keyscan github.com >> ~/.ssh/known_hosts

          # Pull latest changes
          git pull origin main
          
          # Ensure Docker Compose is installed
          if ! command -v docker-compose &> /dev/null; then
            sudo apt update && sudo apt install -y docker-compose
          fi
          
          docker-compose down
          docker-compose up -d --build
          EOF
